name: Dynamic Application Security Testing (DAST)
on:
    workflow_dispatch:
        inputs:
            selected-branch:
                description: 'Branch to scan'
                required: true
                type: string
                default: 'Please input a branch'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
